#:kivy 2.0.0
#:import utils kivy.utils
#:import Icons ui.icons.Icons
#:set margin 10


<Bottom>:
    canvas:
        Color:
            rgba: (30/255, 35/255, 40/255, 0.9)
        RoundedRectangle:
            pos: (self.x + margin, self.y + margin)
            size: (self.width - (2 * margin), self.height - (2 * margin))
            radius: [18, 18, 18, 18]
            
    BoxLayout:
        pos: (root.x + margin, root.y + margin)
        size: (root.width - 2*margin, root.height - 2*margin)
        padding: 8
        spacing: 8

        RoundedButton:
            text: "[font=Icons]" + Icons.camera + "[/font]  CAM"
            btn_color: (50/255, 55/255, 60/255, 1) 
            size_hint_x: None
            width: self.height + 40
            on_release: app.on_action("CAM")

        Divider:
            size_hint_y: 0.6
            pos_hint: {"center_y": 0.5}

        RoundedButton:
            text: ("[font=Icons]" + Icons.arrow_bottom_right + "[/font]  LAND") if root.is_flying else ("[font=Icons]" + Icons.arrow_top_right + "[/font]  TAKE OFF")
            btn_color: (220/255, 60/255, 30/255, 1) if root.is_flying else (0/255, 160/255, 230/255, 1)
            bold: True
            font_size: '18sp'
            on_release: root.toggle_flight()

        Divider:
            size_hint_y: 0.6
            pos_hint: {"center_y": 0.5}

        RoundedButton:
            text: ("[font=Icons]" + Icons.content_save + "[/font]  SAVE") if root.is_recording else ("[font=Icons]" + Icons.video + "[/font]  REC")
            btn_color: (40/255, 60/255, 40/255, 1) if root.is_recording else (60/255, 40/255, 40/255, 1) 
            text_color: (0.3, 1, 0.3, 1) if root.is_recording else (1, 0.3, 0.3, 1)
            size_hint_x: None
            width: self.height + 40
            on_release: root.toggle_record()